import type { ThemeRegistration } from 'shiki';

/** JetBrains Darcula as a TextMate theme for Shiki/Monaco (spec §12.1: "custom Darcula JSON"). Shiki
 * doesn't ship one; the colours are IntelliJ's `Darcula.xml` scheme defaults. */
export const darcula: ThemeRegistration = {
  name: 'darcula',
  displayName: 'Darcula',
  type: 'dark',
  colors: {
    'editor.background': '#2B2B2B',
    'editor.foreground': '#A9B7C6',
    'editorLineNumber.foreground': '#606366',
    'editorLineNumber.activeForeground': '#A4A3A3',
    'editorGutter.background': '#313335',
    'editor.selectionBackground': '#214283',
    'editor.inactiveSelectionBackground': '#21428380',
    'editor.lineHighlightBackground': '#323232',
    'editorCursor.foreground': '#BBBBBB',
    'editorWhitespace.foreground': '#404040',
    'editorIndentGuide.background1': '#373737',
    'editorIndentGuide.activeBackground1': '#505050',
    'editor.findMatchBackground': '#32593D',
    'editor.findMatchHighlightBackground': '#32593D80',
    'diffEditor.insertedLineBackground': '#29443680',
    'diffEditor.removedLineBackground': '#4A2E2E80',
    'diffEditor.insertedTextBackground': '#3C5A3C99',
    'diffEditor.removedTextBackground': '#6E3B3B99',
    'scrollbarSlider.background': '#4E4E4E80',
    'minimap.background': '#2B2B2B',
  },
  tokenColors: [
    { scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: '#808080', fontStyle: 'italic' } },
    { scope: ['comment.block.documentation', 'comment.block.documentation punctuation.definition.comment'], settings: { foreground: '#629755', fontStyle: 'italic' } },
    { scope: ['string', 'string.quoted', 'string.template', 'punctuation.definition.string'], settings: { foreground: '#6A8759' } },
    { scope: ['constant.character.escape', 'constant.other.placeholder'], settings: { foreground: '#CC7832' } },
    { scope: ['constant.numeric'], settings: { foreground: '#6897BB' } },
    { scope: ['constant.language'], settings: { foreground: '#CC7832' } },
    { scope: ['keyword', 'keyword.control', 'storage', 'storage.type', 'storage.modifier', 'keyword.operator.new', 'keyword.other'], settings: { foreground: '#CC7832' } },
    { scope: ['keyword.operator'], settings: { foreground: '#A9B7C6' } },
    { scope: ['variable.language'], settings: { foreground: '#CC7832' } },
    { scope: ['entity.name.function', 'support.function', 'meta.function-call entity.name.function'], settings: { foreground: '#FFC66D' } },
    { scope: ['entity.name.type', 'entity.name.class', 'support.class', 'entity.other.inherited-class'], settings: { foreground: '#A9B7C6' } },
    { scope: ['variable.other.php', 'variable.other.property', 'variable.other.object.property', 'support.variable.property', 'meta.property-name', 'support.type.property-name'], settings: { foreground: '#9876AA' } },
    { scope: ['variable.other.constant', 'constant.other'], settings: { foreground: '#9876AA', fontStyle: 'italic' } },
    { scope: ['entity.name.tag'], settings: { foreground: '#E8BF6A' } },
    { scope: ['entity.other.attribute-name'], settings: { foreground: '#BABABA' } },
    { scope: ['meta.decorator', 'storage.type.annotation', 'punctuation.decorator', 'entity.name.function.decorator'], settings: { foreground: '#BBB529' } },
    { scope: ['markup.heading'], settings: { foreground: '#CC7832', fontStyle: 'bold' } },
    { scope: ['markup.bold'], settings: { fontStyle: 'bold' } },
    { scope: ['markup.italic'], settings: { fontStyle: 'italic' } },
    { scope: ['markup.inserted'], settings: { foreground: '#629755' } },
    { scope: ['markup.deleted', 'invalid'], settings: { foreground: '#BC3F3C' } },
  ],
};
