//! Types serialized to the UI. TypeScript definitions are generated by ts-rs (`just gen-types`).

use crate::graph::{render_ascii, AsciiRow, NodeKind, Segment};
use crate::remotes::HostKind;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct GraphPayload {
    pub rows: Vec<RowPayload>,
    pub labels: Vec<RefLabel>,
    pub max_lanes: u16,
    pub pinned_ref: Option<String>,
    /// The remote counterpart of a pinned local branch: the default pick's remote trunk (the
    /// branch it stands for), an explicit pin's upstream. Absent when the pin is a remote ref,
    /// has no upstream, or there's no pin. Branch membership ranks it right after the trunk.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub pinned_remote: Option<String>,
    pub head: HeadPayload,
    pub truncated: bool,
    /// The open worktree (the one this tab opened), spelled as its WIP row's
    /// `WipPayload::worktree_path` would be, dirty or not: what "Compare with working tree"
    /// targets. Absent if it isn't among `git worktree list`'s usable ones.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub open_worktree: Option<String>,
    /// Every usable worktree of the repository (spec #2 §11.2).
    pub worktrees: Vec<GraphWorktree>,
    // 2D-T6 begin
    /// Each worktree's merge, rebase or other in-progress operation (spec #2 §13.2), keyed by its
    /// path as its WIP row's `worktreePath` spells it (Deviation 1). Absent when none is mid-operation.
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    #[ts(optional, as = "Option<std::collections::BTreeMap<String, crate::in_progress::InProgress>>")]
    pub in_progress: std::collections::BTreeMap<String, crate::in_progress::InProgress>,
    // 2D-T6 end
}

/// One usable worktree as the graph sees it (spec #2 §11.2): the UI moves the HEAD marker and
/// the "checked out elsewhere" chips to the tab's active worktree from these, with no request.
#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct GraphWorktree {
    /// Spelled as its WIP row's `WipPayload::worktree_path`.
    pub path: String,
    /// The full ref its HEAD names; `None` when detached or bare.
    pub branch: Option<String>,
    pub head: Option<String>,
    pub is_main: bool,
    pub locked: bool,
    /// The operation in progress there, by kind (`merge`, `rebase`, or what git calls the other
    /// one: `cherry-pick`, `revert`, `am`); the detail is in `GraphPayload.in_progress`, keyed by
    /// this path.
    pub in_progress: Option<String>,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RowPayload {
    pub id: String,
    pub kind: NodeKind,
    pub lane: u16,
    pub color: u8,
    /// Packed segments; see `graph::Segment::pack`.
    pub segments: Vec<u32>,
    pub summary: String,
    pub body_first_line: String,
    pub author_name: String,
    pub author_email: String,
    #[ts(type = "number")]
    pub author_time: i64,
    /// Committer timestamp (unix seconds): what the Date/Time column shows. It
    /// differs from `author_time` once a commit is amended, rebased or cherry-picked. 0 on WIP rows.
    #[ts(type = "number")]
    pub committer_time: i64,
    pub parents: Vec<String>,
    /// MR/PR/issue references in the summary and body, as written (`!42`, `group/project!7`,
    /// `#12`, `owner/repo#3`), first occurrence first, at most 20 (`message_refs`, §9.2). The
    /// host decides what each means. Empty on WIP rows.
    pub mr_refs: Vec<String>,
    pub wip: Option<WipPayload>,
}

/// A commit's complete message, fetched on demand (`Request::CommitMessage`) rather than carried
/// by every graph row: the full-message tooltip (§8.4) and the details panel (§9.2) use it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct CommitMessage {
    pub id: String,
    /// The first line.
    pub summary: String,
    /// Everything after the first line, line breaks kept, surrounding whitespace trimmed.
    pub body: String,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct WipPayload {
    pub worktree_path: String,
    pub worktree_name: Option<String>,
    pub modified: u32,
    pub added: u32,
    pub deleted: u32,
    pub renamed: u32,
    pub conflicted: u32,
}

#[derive(Debug, Clone, Default, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct HeadPayload {
    pub branch: Option<String>,
    pub target: Option<String>,
    pub detached: bool,
    pub unborn: bool,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RefLabel {
    pub row: u32,
    pub name: String,
    pub local: Option<String>,
    pub remotes: Vec<RemoteRefLabel>,
    pub tag: bool,
    pub is_head: bool,
    pub worktree: Option<String>,
    /// The worktree (any, the open one included) whose HEAD is this local branch.
    pub checked_out: Option<String>,
    /// A local branch whose upstream has another branch name (`feature/a` tracking
    /// `origin/feature/b`): that upstream's short name, for the chip's warning (UX round 3, M.1).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub upstream_mismatch: Option<String>,
    /// An annotated tag's message and tagger (UX round 3, M.2); absent on a lightweight tag.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub annotation: Option<TagAnnotation>,
}

/// An annotated tag's message and tagger, for the tag chip's and the sidebar row's tooltip (UX
/// round 3, M.2). Read in process with the refs, cached by tag object (`refs::read_tag`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct TagAnnotation {
    /// The message's first `refs::TAG_MESSAGE_LINES` lines (any signature left out), trimmed.
    pub message: String,
    /// More of the message follows.
    pub truncated: bool,
    /// The tagger's name.
    pub tagger: Option<String>,
    /// When it was tagged (unix seconds); 0 without a tagger.
    #[ts(type = "number")]
    pub time: i64,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RemoteRefLabel {
    pub full_name: String,
    pub remote: String,
    /// The remote's host name, so the UI can apply the profile's host-type override.
    pub host: Option<String>,
    pub host_kind: HostKind,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RepoSummary {
    pub id: u32,
    pub path: String,
    pub name: String,
    /// The canonical worktree the opened path is in. `path` is the repository's (its main
    /// worktree), shared by every tab on it (spec #2 §11.2).
    pub worktree: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct PersonPayload {
    pub name: String,
    pub email: String,
    #[ts(type = "number")]
    pub time: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct CoAuthor {
    pub name: String,
    pub email: String,
}

/// The right panel's commit header (spec §9.1). The message itself (§9.2) is not here: the panel
/// gets it from `Request::CommitMessage`, sharing the graph tooltip's cache.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct CommitDetailsPayload {
    pub id: String,
    pub parents: Vec<String>,
    pub author: PersonPayload,
    pub committer: PersonPayload,
    pub co_authors: Vec<CoAuthor>,
    /// The raw commit has a signature header (`gpgsig`). Verification is lazy (`signature`).
    pub signed: bool,
}

/// A remote's parsed URL (spec §14.4). The URL itself is never sent: it may carry a token.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RemotePayload {
    pub name: String,
    pub host: Option<String>,
    pub path: Option<String>,
    pub host_kind: HostKind,
    /// The repo's chosen main remote (`RepoSettings::forge_target_remote`). Server-side only.
    #[serde(skip)]
    #[ts(skip)]
    pub main: bool,
}

/// Where one side of a file diff comes from (spec §10.2). The file list builds these and the
/// diff viewer sends them back unchanged (`diffContents`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export)]
pub enum BlobSource {
    /// The side doesn't exist (an added or deleted file).
    Absent,
    Object { oid: String },
    /// A gitlink; shown as `Subproject commit <oid>`, like git.
    Submodule { oid: String },
    /// The file at `commit` (File View of an unchanged file, spec §9.3).
    AtCommit { commit: String },
    /// The file in a worktree (WIP and compare-with-working-tree).
    Worktree { worktree: String },
}

/// An unmerged path's conflict (spec #2 §7.1), from `git status`'s two-letter code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum ConflictKind {
    BothModified,
    BothAdded,
    BothDeleted,
    AddedByUs,
    AddedByThem,
    DeletedByUs,
    DeletedByThem,
}

impl ConflictKind {
    /// Porcelain v2's `XY` of a `u` entry.
    pub fn from_xy(x: char, y: char) -> Option<Self> {
        Some(match (x, y) {
            ('U', 'U') => Self::BothModified,
            ('A', 'A') => Self::BothAdded,
            ('D', 'D') => Self::BothDeleted,
            ('A', 'U') => Self::AddedByUs,
            ('U', 'A') => Self::AddedByThem,
            ('D', 'U') => Self::DeletedByUs,
            ('U', 'D') => Self::DeletedByThem,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct FileChange {
    pub path: String,
    /// The source path of a rename or copy.
    pub old_path: Option<String>,
    /// `A`, `C`, `D`, `M`, `R`, `T`, `U` or `X`.
    pub status: String,
    /// `None` for binary files.
    pub additions: Option<u32>,
    pub deletions: Option<u32>,
    pub old: BlobSource,
    pub new: BlobSource,
    pub submodule: bool,
    /// An unmerged WIP path's conflict kind; absent everywhere else.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub conflict: Option<ConflictKind>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct FileListPayload {
    pub files: Vec<FileChange>,
    /// Line totals over the text files (spec §9.3 header).
    pub added: u32,
    pub deleted: u32,
    /// A WIP list kept by the active tab's watcher (K44): the version of that worktree's lists,
    /// which a `repoChanged` naming the worktree replaces. The UI may hold such a list until
    /// then. Absent for every other list, and for WIP lists read without a trusted watcher.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub version: Option<String>,
}

/// The signature badge (spec §9.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum SignatureKind {
    Verified,
    Unverified,
    Bad,
    Expired,
    UnknownKey,
    Unsigned,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SignaturePayload {
    pub kind: SignatureKind,
    pub signer: String,
    pub key: String,
    pub fingerprint: String,
    /// GPG trust level (`fully`, `ultimate`, …); empty when git has none.
    pub trust: String,
    pub detail: Option<String>,
}

impl GraphPayload {
    /// ASCII dump: layout grid, then the row summary (WIP rows show their worktree).
    pub fn ascii(&self) -> String {
        let segs: Vec<Vec<Segment>> = self.rows.iter().map(|r| r.segments.iter().map(|&s| Segment::unpack(s)).collect()).collect();
        let labels: Vec<String> = self
            .rows
            .iter()
            .map(|r| match &r.wip {
                Some(w) => format!("// WIP {}", w.worktree_name.as_deref().unwrap_or("(main)")),
                None => r.summary.clone(),
            })
            .collect();
        let rows: Vec<AsciiRow> = self
            .rows
            .iter()
            .zip(&segs)
            .zip(&labels)
            .map(|((r, s), l)| AsciiRow { lane: r.lane, kind: r.kind, segments: s, label: l })
            .collect();
        render_ascii(&rows, self.max_lanes)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "lowercase")]
#[ts(export)]
pub enum Eol {
    Lf,
    Crlf,
    Mixed,
    None,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct BlobPayload {
    #[ts(type = "number")]
    pub size: u64,
    pub binary: bool,
    /// e.g. `UTF-8`, `UTF-8 BOM`, `UTF-16LE`, `ISO-8859-1`; empty for binary or unloaded sides.
    pub encoding: String,
    pub eol: Eol,
    /// Decoded text; `None` for binary files and for sides held back by the large-file prompt.
    pub text: Option<String>,
    /// Raw bytes, base64, for binary images only (spec §10.4).
    pub base64: Option<String>,
    /// The loaded bytes' `worktree_id` (2B Deviation 12): the save base of a working-tree side.
    /// `None` when the side wasn't loaded (too large).
    pub hash: Option<String>,
    /// A working-tree side whose `text` is its clean form, as git compares it, and that form
    /// differs from the file by more than line endings (a `filter` driver, `ident`): the text
    /// isn't the file's, so it's read-only. Absent otherwise.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    #[ts(optional, as = "Option<bool>")]
    pub filtered: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct DiffContentsPayload {
    pub old: Option<BlobPayload>,
    pub new: Option<BlobPayload>,
    /// A side is over 2 MiB and `force` was false: show "Large file — load anyway?". Even with
    /// `force`, a side over 64 MiB (`MAX_FORCED_BYTES`) stays `too_large`: that size is never loaded.
    pub too_large: bool,
    /// Only the line endings changed (spec §10.2 banner).
    pub eol_only: bool,
    /// The path has a raster-image extension (the UI shows the image diff).
    pub image: bool,
}

/// One side of a binary file as a hex dump (`hexDump`): `hexdump -C` lines of its first
/// `shown` bytes, at most `HexDumpPayload::cap`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct HexSide {
    /// The whole side's size in bytes.
    #[ts(type = "number")]
    pub size: u64,
    /// How many bytes `dump` covers: `size`, or the cap when the side is larger.
    #[ts(type = "number")]
    pub shown: u64,
    pub dump: String,
}

/// Both sides of a binary file as hex dumps, for File View and the hex diff. `None`: no such side
/// (an added or deleted file).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct HexDumpPayload {
    pub old: Option<HexSide>,
    pub new: Option<HexSide>,
    /// The most bytes dumped per side.
    #[ts(type = "number")]
    pub cap: u64,
}
