//! Types serialized to the UI. TypeScript definitions are generated by ts-rs (`just gen-types`).

use crate::graph::{render_ascii, AsciiRow, NodeKind, Segment};
use crate::remotes::HostKind;
use serde::Serialize;
use ts_rs::TS;

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct GraphPayload {
    pub rows: Vec<RowPayload>,
    pub labels: Vec<RefLabel>,
    pub max_lanes: u16,
    pub pinned_ref: Option<String>,
    pub head: HeadPayload,
    pub truncated: bool,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RowPayload {
    pub id: String,
    pub kind: NodeKind,
    pub lane: u16,
    pub color: u8,
    /// Packed segments; see `graph::Segment::pack`.
    pub segments: Vec<u32>,
    pub summary: String,
    pub body_first_line: String,
    pub author_name: String,
    pub author_email: String,
    #[ts(type = "number")]
    pub author_time: i64,
    pub parents: Vec<String>,
    pub wip: Option<WipPayload>,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct WipPayload {
    pub worktree_path: String,
    pub worktree_name: Option<String>,
    pub modified: u32,
    pub added: u32,
    pub deleted: u32,
    pub conflicted: u32,
}

#[derive(Debug, Clone, Default, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct HeadPayload {
    pub branch: Option<String>,
    pub target: Option<String>,
    pub detached: bool,
    pub unborn: bool,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RefLabel {
    pub row: u32,
    pub name: String,
    pub local: Option<String>,
    pub remotes: Vec<RemoteRefLabel>,
    pub tag: bool,
    pub is_head: bool,
    pub worktree: Option<String>,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RemoteRefLabel {
    pub full_name: String,
    pub remote: String,
    pub host_kind: HostKind,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RepoSummary {
    pub id: u32,
    pub path: String,
    pub name: String,
}

impl GraphPayload {
    /// ASCII dump: layout grid, then the row summary (WIP rows show their worktree).
    pub fn ascii(&self) -> String {
        let segs: Vec<Vec<Segment>> = self.rows.iter().map(|r| r.segments.iter().map(|&s| Segment::unpack(s)).collect()).collect();
        let labels: Vec<String> = self
            .rows
            .iter()
            .map(|r| match &r.wip {
                Some(w) => format!("// WIP {}", w.worktree_name.as_deref().unwrap_or("(main)")),
                None => r.summary.clone(),
            })
            .collect();
        let rows: Vec<AsciiRow> = self
            .rows
            .iter()
            .zip(&segs)
            .zip(&labels)
            .map(|((r, s), l)| AsciiRow { lane: r.lane, kind: r.kind, segments: s, label: l })
            .collect();
        render_ascii(&rows, self.max_lanes)
    }
}
