#!/usr/bin/env bash
# Usage: scripts/package-arch.sh <package.deb> [out-dir]
#
# Turns the built (and fix-deb'ed) .deb into an Arch package, GitBolt-<ver>-1-x86_64.pkg.tar.zst,
# without makepkg (the build machine is Ubuntu). out-dir defaults to target/release/bundle/arch.
#   payload  = the .deb's data member: same paths and modes (chrome-sandbox stays root:root 4755),
#              plus usr/share/licenses/gitbolt -> ../doc/gitbolt (the license notices)
#   .PKGINFO = pacman's key = value metadata; depends mapped from the .deb's Depends through the
#              table in scripts/arch-pkg.py (an unknown Debian name fails the build)
#   .MTREE   = gzip'd mtree of .PKGINFO and the payload, as makepkg's bsdtar writes it
# Archive order: .PKGINFO, .MTREE, then the payload; GNU tar, every entry root:root with one fixed
# mtime (the version's +YYYYMMDDHHMM build stamp, or $SOURCE_DATE_EPOCH), zstd -19.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
helper="$here/arch-pkg.py"
deb=$(realpath "${1:?usage: package-arch.sh <package.deb> [out-dir]}")
out=${2:-target/release/bundle/arch}
fail() { echo "package-arch: $*" >&2; exit 1; }
[ -f "$deb" ] || fail "no such file: $deb"
mkdir -p "$out"
out=$(realpath "$out")

debver=$(dpkg-deb -f "$deb" Version)
pkgver=$(python3 "$helper" pkgver "$debver")-1
epoch=${SOURCE_DATE_EPOCH:-$(python3 "$helper" stamp "$debver" 2>/dev/null || stat -c %Y "$deb")}
pkgdesc=$(dpkg-deb -f "$deb" Description | head -1)
mapfile -t depends < <(python3 "$helper" depends "$(dpkg-deb -f "$deb" Depends)")
[ ${#depends[@]} -gt 0 ] || fail "no dependencies mapped"

# The work dir sits next to the output, not in /tmp (often tmpfs): the payload is ~350 MB.
work=$(mktemp -d "$out/.work.XXXXXX"); trap 'rm -rf "$work"' EXIT
(cd "$work" && ar x "$deb")
[ -f "$work/debian-binary" ] || fail "not a .deb: $deb"
data=$(cd "$work" && ls data.tar.*)
case "$data" in
  *.gz) unpack=(gzip -dc) ;;
  *.xz) unpack=(xz -dc) ;;
  *.zst) unpack=(zstd -dcq) ;;
  *.tar) unpack=(cat) ;;
  *) fail "unknown data member compression: $data" ;;
esac
"${unpack[@]}" "$work/$data" > "$work/data.tar"
rm "$work/$data"
mkdir "$work/pkg"
# -p keeps the recorded modes (the owner may set setuid on its own file); a normal user can't
# chown, so ownership is set in the archive below instead.
tar -xpf "$work/data.tar" -C "$work/pkg" --no-same-owner
[ -e "$work/pkg/.PKGINFO" ] && fail "the .deb's payload has a .PKGINFO"
sandbox=$(find "$work/pkg" -name chrome-sandbox -type f)
[ -n "$sandbox" ] || fail "no chrome-sandbox in the payload"
chmod 4755 "$sandbox" # as the deb ships it; never drop the setuid bit

# The license notices (docs/licensing.md) are in the .deb's /usr/share/doc/gitbolt/. Arch looks
# for license files in /usr/share/licenses/<pkg>/, so that is a symlink to the same directory.
for f in LICENSE THIRD-PARTY-NOTICES-rust.txt THIRD-PARTY-NOTICES-ui.txt CEF-LICENSE.txt CHROMIUM-CREDITS.html.gz DICTIONARY-en-US-LICENSE.txt; do
  [ -s "$work/pkg/usr/share/doc/gitbolt/$f" ] || fail "the .deb has no usr/share/doc/gitbolt/$f (or it's empty)"
done
# The spell-check dictionary the app copies into Chromium's profile (PRIVACY.md).
[ -s "$work/pkg/usr/share/GitBolt/dictionaries/en-US-10-1.bdic" ] ||
  fail "the .deb has no usr/share/GitBolt/dictionaries/en-US-10-1.bdic (or it's empty)"
[ -e "$work/pkg/usr/share/licenses/gitbolt" ] && fail "the .deb's payload already has usr/share/licenses/gitbolt"
mkdir -p "$work/pkg/usr/share/licenses"
chmod 755 "$work/pkg/usr/share/licenses"
ln -s ../doc/gitbolt "$work/pkg/usr/share/licenses/gitbolt"

size=$(python3 "$helper" size "$work/pkg")
{
  echo "# Generated by scripts/package-arch.sh from $(basename "$deb")"
  echo "pkgname = gitbolt"
  echo "pkgbase = gitbolt"
  echo "xdata = pkgtype=pkg"
  echo "pkgver = $pkgver"
  echo "pkgdesc = $pkgdesc"
  echo "url = https://github.com/GitBoltApp/gitbolt"
  echo "builddate = $epoch"
  echo "packager = GitBolt build"
  echo "size = $size"
  echo "arch = x86_64"
  echo "license = MIT"
  printf 'depend = %s\n' "${depends[@]}"
} > "$work/pkg/.PKGINFO"
chmod 644 "$work/pkg/.PKGINFO"
python3 "$helper" mtree "$work/pkg" "$epoch" "$work/pkg/.MTREE"
chmod 644 "$work/pkg/.MTREE"

name="GitBolt-$pkgver-x86_64.pkg.tar.zst"
mapfile -t payload < <(cd "$work/pkg" && find . -mindepth 1 -maxdepth 1 ! -name '.*' -printf '%P\n' | LC_ALL=C sort)
tar -C "$work/pkg" --format=gnu --sort=name --mtime="@$epoch" \
    --owner=root:0 --group=root:0 --no-recursion -cf "$work/meta.tar" .PKGINFO .MTREE
tar -C "$work/pkg" --format=gnu --sort=name --mtime="@$epoch" \
    --owner=root:0 --group=root:0 -rf "$work/meta.tar" "${payload[@]}"
mv "$work/meta.tar" "$work/pkg.tar"

# The payload must match the .deb entry for entry (plus the licenses symlink), and stay root-owned
# and setuid.
python3 "$helper" verify "$work/data.tar" "$work/pkg.tar" >/dev/null
[ "$(tar -tf "$work/pkg.tar" | head -2 | tr '\n' ' ')" = ".PKGINFO .MTREE " ] || fail "the archive doesn't start with .PKGINFO, .MTREE"
line=$(tar -tvf "$work/pkg.tar" | grep '/chrome-sandbox$') || fail "no chrome-sandbox in the package"
[[ $line == -rwsr-xr-x\ root/root* ]] || fail "chrome-sandbox is not root:root 4755: $line"

rm -f "$out"/GitBolt-*-x86_64.pkg.tar.zst
zstd -19 -T0 -q --rm "$work/pkg.tar" -o "$out/$name"
echo "package-arch: $out/$name ($(du -h "$out/$name" | cut -f1)); pkgver $pkgver; depends: ${depends[*]}"
