[package]
name = "gitbolt-forge"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
gitbolt-core.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
base64.workspace = true
sha2.workspace = true
ureq.workspace = true
keyring.workspace = true
nix.workspace = true
httpdate.workspace = true
tempfile.workspace = true
