[package]
name = "gitbolt-core"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
testing = []

[dependencies]
gix.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
regex.workspace = true
nix.workspace = true
ts-rs.workspace = true
tempfile.workspace = true
encoding_rs.workspace = true
base64.workspace = true

[dev-dependencies]
insta.workspace = true
